@startuml
Class Resource
Class Availability
Class Viva
Class Student
Class Teacher
Class External

Resource : id : ResourceId
Resource : name : Name
Resource : availability : List[Availability]

Availability : start : DateTime
Availability : end : DateTime
Availability : preference : Preference

Viva : student : Student
Viva : title : Title
Viva : jury : List[Role]
Viva : start : DateTime
Viva : end : DateTime
Viva : preference : SummedPreference

Student : name : String

Resource <|-- Teacher : extends
Resource <|-- External : extends
Viva "1" - "*" Resource
Viva "1" - "1" Availability
Resource "1" -- "0..*" Availability
Student "1" - "1" Viva
@enduml